MODEL_PATH = 'saved_model'
CHECKPOINT_PATH = 'checkpoint'
DATA_NUM = 500  # None for all data
SEQ_LENGTH = 100
EPOCHS = 20
BATCH_SIZE = 64
EMBEDDING_DIM = 512
RNN_UNITS = 1024
LEARNING_RATE = 0.001
TEMPERATURE = 0.8  # bigger value means bigger randomness, and vice versa
